---
fixes:
  - |
    Updates the default Grafana OpenSearch datasource configuration to use
    values for OpenSearch that work out of the box. Replaces the Elasticsearch
    values that were previously being used. The new configuration can be
    applied by deleting your datasource and reconfiguring Grafana through kolla
    ansible. In order to prevent dashboards from breaking when the datasource
    is deleted, one should use `datasource variables
    <https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#add-a-data-source-variable>`__
    in Grafana. See bug `2039500 <https://bugs.launchpad.net/kolla-ansible/+bug/2039500>`__.
