---
upgrade:
  - |
    Horizon role was reworked to preffered local_settings.d
    configuration model. Files ``local_settings`` and
    ``custom_local_settings`` were renamed to ``_9998-kolla-settings.py``
    and ``_9999-custom-settings.py`` Users who use horizon's custom
    configuration have to change the names of those files in
    ``/etc/kolla/config/horizon`` also.
