---
features:
  - |
    Allow overriding of Skyline configuration files by supplying your own
    version of nginx.conf for Skyline Console, gunicorn.py and skyline.yaml
    for  Skyline API Server. Place the files in the skyline subfolder of
    your Kolla config directory, skyline.yaml will be merged with the
    Kolla provided version.
