---
name: Lint

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: { }

jobs:
  AnsibleLint:
    runs-on: ubuntu-latest     # name of a container (environment) to run your automations in
    steps:
      - name: check code out from github and into "ubuntu-latest" (or our environment)
        uses: actions/checkout@v4
      - name: lint ansible playbook playbook.yml
        uses: actions/setup-python@v5.1.0
        with:
            python-version: '3.10' 
      - run: python -m pip install -r  lint-requirements.txt && python -m pip install jmespath && python -m pip install -r requirements.txt && ansible-galaxy install -r requirements.yml && ansible-lint 
