---
name: Lint

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: { }

jobs:
  AnsibleLint:
    runs-on: ubuntu-latest     # name of a container (environment) to run your automations in
    steps:
      - name: check code out from github and into "ubuntu-latest" (or our environment)
        uses: actions/checkout@v4
      - name: lint ansible playbook playbook.yml
        uses: ansible/ansible-lint@main   # this is there branch
